
import { 
  MarketplaceCategory, 
  MarketplaceItem, 
  ItemStatus, 
  TechItem, 
  MediaItem, 
  CulinaryItem 
} from '../types';

export const initialMockItems: MarketplaceItem[] = [
  {
    id: '1',
    name: 'MacBook Pro M3 Max',
    sku: 'AAPL-MBP-M3-14',
    price: 3499,
    salePrice: 3299,
    isOffer: true,
    description: 'The ultimate portable workstation with M3 Max chip.',
    status: ItemStatus.PUBLISHED,
    marketplace: MarketplaceCategory.TECH,
    categories: ['Developer', 'Office Laptop'],
    images: ['https://picsum.photos/id/0/400/400'],
    availabilityStatus: 'In Stock',
    brand: 'Apple',
    type: 'Laptop',
    condition: 'New',
    color: 'Space Black',
    size: '14-inch',
    weight: 1.6,
    warranty: { hasWarranty: true, duration: '1 Year' },
    specs: { RAM: '64GB', SSD: '2TB' },
    audit: {
      createdAt: '2024-01-10T10:00:00Z',
      createdBy: 'System',
      updatedAt: '2024-03-15T14:30:00Z',
      updatedBy: 'Admin'
    }
  } as TechItem,
  {
    id: '2',
    name: 'Logitech MX Master 3S',
    sku: 'LOGI-MXM3S',
    price: 99,
    isOffer: false,
    description: 'Performance wireless mouse with silent clicks.',
    status: ItemStatus.PUBLISHED,
    marketplace: MarketplaceCategory.TECH,
    categories: ['Peripherals', 'Office Laptop'],
    images: ['https://picsum.photos/id/10/400/400'],
    availabilityStatus: 'In Stock',
    brand: 'Logitech',
    type: 'Accessory',
    condition: 'New',
    color: 'Pale Gray',
    size: 'Standard',
    weight: 0.14,
    warranty: { hasWarranty: true, duration: '2 Years' },
    specs: { DPI: '8000', Battery: 'Rechargeable' },
    audit: {
      createdAt: '2024-02-12T09:00:00Z',
      createdBy: 'System',
      updatedAt: '2024-02-12T09:00:00Z',
      updatedBy: 'System'
    }
  } as TechItem,
  {
    id: '3',
    name: 'Premium Leather Bound Notebook',
    sku: 'MD-NB-LEA-01',
    price: 45,
    isOffer: false,
    description: 'Handcrafted leather notebook for high-end corporate gifts.',
    status: ItemStatus.DRAFT,
    marketplace: MarketplaceCategory.MEDIA,
    categories: ['Stationery'],
    images: ['https://picsum.photos/id/24/400/400'],
    availabilityStatus: 'Pre-order',
    material: 'Full Grain Leather',
    finish: 'Matte',
    color: 'Saddle Brown',
    dimensions: { length: 21, width: 14.8, height: 2 },
    weight: 0.4,
    customizable: true,
    productionMethod: 'Handmade',
    customizationOptions: ['Embossing', 'Hot Stamping'],
    minOrderQuantity: 50,
    leadTime: 14,
    packagingType: 'Premium Box',
    audit: {
      createdAt: '2024-03-01T11:00:00Z',
      createdBy: 'Marketing_Jane',
      updatedAt: '2024-03-01T11:00:00Z',
      updatedBy: 'Marketing_Jane'
    }
  } as MediaItem,
  {
    id: '4',
    name: 'Truffle Infused Wagyu Burger',
    sku: 'CUL-BGR-TRF',
    price: 28,
    salePrice: 22,
    isOffer: true,
    description: 'Aged Wagyu beef with black truffle aioli and brioche.',
    status: ItemStatus.PUBLISHED,
    marketplace: MarketplaceCategory.CULINARY,
    categories: ['Meals'],
    images: ['https://picsum.photos/id/30/400/400'],
    availabilityStatus: 'In Stock',
    cuisineType: 'Intercontinental',
    dietaryTags: ['Halal'],
    preparationType: 'Ready-to-Eat',
    spiceLevel: 'None',
    portionSize: 'Large',
    ingredients: ['Wagyu Beef', 'Truffle Oil', 'Brioche Bun'],
    allergens: ['Gluten', 'Dairy'],
    nutritionalInfo: { Calories: 850, Protein: '45g' },
    weightVolume: '450g',
    shelfLife: '1 Day',
    storageInstructions: 'Keep Refrigerated',
    preparationInstructions: 'Heat for 2 minutes in microwave or oven.',
    availabilityWindow: '11 AM - 10 PM',
    deliveryConstraints: 'Within 5km radius',
    audit: {
      createdAt: '2024-03-20T12:00:00Z',
      createdBy: 'Chef_Mario',
      updatedAt: '2024-03-21T08:15:00Z',
      updatedBy: 'Chef_Mario'
    }
  } as CulinaryItem
];
